matrix:
  include:
    - language: android
      dist: trusty
      cache: npm
      android:
        components:
          # use the latest revision of Android SDK Tools
          - tools
          - platform-tools

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      before_install:
        - cd template
        - yes | sdkmanager "platforms;android-29"
        - yes | sdkmanager "build-tools;29.0.2"
      install:
        - nvm install 12.14.0
        - npm i
      before_script:
        - cd android
      script:
        - ./gradlew assembleRelease

    - language: objective-c
      os: osx
      osx_image: xcode12.5
      podfile: template/ios/Podfile
      cache:
        - cocoapods
        - npm
      before_install:
        - cd template
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - gem install cocoapods
        - nvm install 12.14.0
        - npm i
      before_script:
        - cd ios
        - pod install
        - cd ..
      script:
        - npm run ios --configuration Release
